--- # Connection
# ansible-playbook user.yaml 
# link: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Install packages
  hosts: all
  tasks: 
  - name: Add users
    user:
      name: "{{ item }}"
      state: present
    with_items:
    - ben
    - johnd
    - lisa
